Better Texture Width/Height/Format
aers/FFXIVClientStructs pull request #1065
Opened 2024-07-22 23:22 UTC by Exter-N

- Attempts to give better names to `Width`, `Height`, `Width2` and `Height2`, following observations of cases where they differ ;
- Describes more `TextureFormat` values, according to `FUN_1403f0700` and [DXGI_FORMAT](https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format).

2024-07-24 18:41 UTC, wolfcomp commented
Lumina gets their data from the `.dat` files and maps the IDs from there. It could very much be that they are converting said data after the fact in the engine.

2024-08-03 16:27 UTC, Soreepeong commented
unorm 2/3: the game converts 5551 and 4444 to 8888 upon reading the texture before uploading to gpu.

2024-08-26 22:01 UTC, wolfcomp requested changes
Just a few changes for it to be good.

2024-08-26 22:01 UTC, wolfcomp commented on FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Texture.cs
> +    B8G8R8A8_UNORM_4 = 0x1130,
Probably named `L8_UNORM` but this is guessing based on what Lumina has documented

2024-08-30 02:55 UTC, merged