Add content to AgentLookingForGroup
aers/FFXIVClientStructs pull request #1087
Opened 2024-08-09 00:52 UTC by Infiziert90

Most of the `Detailed` struct fits the packet PartyFinderListing, so i sticked with names used in that packet

2024-08-09 10:37 UTC, Haselnussbomber requested changes
Some FixedSizeArray name fixes.

2024-08-09 10:37 UTC, Haselnussbomber commented on FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLookingForGroup.cs
> +        [FieldOffset(0x330), FixedSizeArray(isString: true)] internal FixedSizeArray192<byte> __comment;
```suggestion
        [FieldOffset(0x330), FixedSizeArray(isString: true)] internal FixedSizeArray192<byte> _comment;
```

2024-08-09 10:37 UTC, Haselnussbomber commented on FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLookingForGroup.cs
> +        [FieldOffset(0x3B0), FixedSizeArray(isString: true)] internal FixedSizeArray192<byte> __comment;
```suggestion
        [FieldOffset(0x390), FixedSizeArray(isString: true)] internal FixedSizeArray32<byte> _leader;
        [FieldOffset(0x3B0), FixedSizeArray(isString: true)] internal FixedSizeArray192<byte> _comment;
```

2024-08-16 19:48 UTC, Krepyn commented
0x3104 offset is Recruitment Criteria(lookingforgroupcondition addon) tab, this part 0-1-2 respectively
![image](https://github.com/user-attachments/assets/a3c41df5-2989-46e6-94a0-7f0fffd1fecf)

2024-09-12 03:51 UTC, merged