ActionTimeline methods
aers/FFXIVClientStructs pull request #717
Opened 2023-12-02 00:35 UTC by AsgardXIV

Just adding a few more methods.
Also looks like GetHeightAdjustActionTimelineRowId ended up in the wrong ActionTimelineManager in data, so that's fixed too.

2023-12-13 16:26 UTC, AsgardXIV commented
This should be good to go now. 
Let me know if there are any concerns.

2023-12-15 06:05 UTC, wolfcomp requested changes

2023-12-15 06:09 UTC, AsgardXIV commented on FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
> +    public partial void SetLipsOverrideTimeline(uint slot, ushort actionTimelineId);
That's correct. 970 is the offset to ActionTimelineManager in Character

2023-12-15 06:40 UTC, wolfcomp commented on FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
> +    public partial void SetLipsOverrideTimeline(uint slot, ushort actionTimelineId);
a2 would be the `actionTimelineId` as it's a `ushort` when looking through the disassembly

2023-12-15 06:49 UTC, AsgardXIV commented on FFXIVClientStructs/FFXIV/Client/Game/ActionTimelineManager.cs
> +    public partial void SetLipsOverrideTimeline(uint slot, ushort actionTimelineId);
Oh, I see what you mean. It's a copy paste error from the method above.
It only has the one argument (timelineId), a1 is the this pointer as it's a member function.

Should be fixed now

2023-12-15 08:45 UTC, merged