Add some funcs and vtable names
aers/FFXIVClientStructs pull request #751
Opened 2024-01-11 07:04 UTC by wolfcomp

Added most classes for public content and moved std::vector to be a class definition
Fixed a case where there was a double define of a dtor

2024-01-11 09:50 UTC, Haselnussbomber commented
Couple times you mispelled `PuclicContent`.

2024-01-11 12:19 UTC, Haselnussbomber requested changes

2024-01-11 12:19 UTC, Haselnussbomber commented on ida/data.yml
> +        base: Client::Game::InstanceContent::PuclicContentBozja
Puclic -> Public, now as suggestion.^^

```suggestion
  Client::Game::InstanceContent::PublicContentBozja:
    vtbls:
      - ea: 0x141C36828
        base: Client::Game::InstanceContent::PublicContentDirector
    funcs:
      0x1414B8A00: ctor
  Client::Game::InstanceContent::PublicContentSoutherFront:
    vtbls:
      - ea: 0x141C373D0
        base: Client::Game::InstanceContent::PublicContentBozja
    funcs:
      0x1414B9210: ctor
  Client::Game::InstanceContent::PublicContentDelubrum:
    vtbls:
      - ea: 0x141C396D0
        base: Client::Game::InstanceContent::PublicContentDirector
    funcs:
      0x1414B96B0: ctor
  Client::Game::InstanceContent::PublicContentDelubrumSavage:
    vtbls:
      - ea: 0x141C3A280
        base: Client::Game::InstanceContent::PublicContentDirector
    funcs:
      0x1414B9740: ctor
  Client::Game::InstanceContent::PublicContentZadnor:
    vtbls:
      - ea: 0x141C37F78
        base: Client::Game::InstanceContent::PublicContentBozja
```

2024-01-12 07:58 UTC, Soreepeong reviewed
Multiple instances of `std::vector<T>` should be made, as the differences in `T` does matter.

2024-01-12 07:58 UTC, Soreepeong commented on ida/data.yml
> +      0x140335660: SetSize
`std::vector<AtkValue>::resize(size_t)`

2024-01-12 07:58 UTC, Soreepeong commented on ida/data.yml
> +      0x140921020: _Buy_raw # according to kizer based on source code for stl
`std::vector<T>::_Buy_raw(size_t)` where `sizeof(T)` is 8.

2024-01-12 07:58 UTC, Soreepeong commented on ida/data.yml
> +      0x1415f1A90: dtor
[`std::vector<T>::_Tidy()`](https://github.com/microsoft/STL/blob/3eac329d1f614ecf138d96c22a3b02f87076bc4a/stl/inc/vector#L2039) where [`std::is_trivially_destructible_v<T>`](https://en.cppreference.com/w/cpp/types/is_destructible) [is `true`](https://github.com/microsoft/STL/blob/3eac329d1f614ecf138d96c22a3b02f87076bc4a/stl/inc/xmemory#L1110C1-L1129).

2024-01-12 07:58 UTC, Soreepeong commented on ida/data.yml
> +  std::vector:
It might not be a good idea to have something called `std::vector` when there exist many variations on `<T>` part.

2024-01-16 10:36 UTC, wolfcomp commented
Closing as part of it was merged with #778

2024-01-16 10:36 UTC, closed without merging