[DawnTrail] Update offsets in GcArmyManager and InstanceContent
aers/FFXIVClientStructs pull request #917
Opened 2024-06-13 21:29 UTC by Nukoooo

2024-06-13 21:32 UTC, Haselnussbomber requested changes

2024-06-13 21:32 UTC, Haselnussbomber commented on FFXIVClientStructs/FFXIV/Client/Game/GcArmyManager.cs
> +
Cool, now I can suggest this here. :joy:
The other fields are still there. They just added a second row of stain ids for the new dye channels.

```suggestion
    [FieldOffset(0x4B)] public byte Stain2MainHand;
    [FieldOffset(0x4C)] public byte Stain2OffHand;
    [FieldOffset(0x4D)] public byte Stain2Head;
    [FieldOffset(0x4E)] public byte Stain2Body;
    [FieldOffset(0x4F)] public byte Stain2Hands;
    [FieldOffset(0x50)] public byte Stain2Legs;
    [FieldOffset(0x51)] public byte Stain2Feet;
```

2024-06-14 13:41 UTC, wolfcomp commented
please rebase to the newest commit

2024-06-14 14:42 UTC, Nukoooo commented
It is so fucked, gonna reopen this PR

2024-06-14 14:42 UTC, closed without merging